In [55]:
import numpy as np

In [5]:
a = np.arange(15).reshape(3, 5)
print(a)
print(a.data)
print(a.dtype.name)
print(a.itemsize)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
int32
4


In [7]:
a = np.zeros(2)

b = np.empty(2)

c = np.ones(2)

d = np.arange(4)

e = np.arange(2, 9, 2)

f = np.linspace(0, 10, num=5)

print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

[0. 0.]
[0. 0.]
[1. 1.]
[0 1 2 3]
[2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]


In [8]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [2]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
print('\n', c)


 [[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [23]:
a = np.array([1, 2])
b = np.array([2, 1])

print(np.add(a, b))
print(np.sum(a))

[3 3]
3


### Ejercicio 1

- Crear una matriz de ceros de tipo entero 3x4.
- Crear una matriz de ceros de tipo entero 3x4 excepto la primera fila que será uno.
- Crear una matriz de ceros de tipo entero 3x4 excepto la última fila que será el rango entre 5 y 8.

In [11]:
a = np.zeros([3, 4])
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
a = np.ones([1, 4])
b = np.zeros([2, 4])

c = np.concatenate((a, b), axis=0)
c

array([[1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [125]:
a = np.arange(5, 9, 1)
b = np.zeros([2, 4])

c = np.concatenate(([a], b), axis=0)
c


array([[5., 6., 7., 8.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Ejercicio 2

- Crea un vector de 10 elementos, siendo los índices impares unos y los índices pares dos.
- Crea un «tablero de ajedrez», con unos en las casillas negras y ceros en las blancas.

In [77]:
a = np.array([])

while np.size(a) < 10:
    if np.size(a) % 2 == 0:
        a = np.concatenate((a, np.array([2])))
    else:
        a = np.concatenate((a, np.array([1])))

print(a)

[2. 1. 2. 1. 2. 1. 2. 1. 2. 1.]


In [135]:
a = np.array([])
b = np.array([])

while np.size(a) < 8:
    if np.size(a) % 2 == 0:
        a = np.concatenate((a, np.array([0])))
    else:
        a = np.concatenate((a, np.array([1])))

while np.size(b) < 8:
    if np.size(b) % 2 == 0:
        b = np.concatenate((b, np.array([1])))
    else:
        b = np.concatenate((b, np.array([0])))

tablero = [a]

fila, columna = np.shape(tablero)
while fila < 8:
    if fila % 2 == 0:
        tablero = np.concatenate((tablero, [b]), axis=0)
        fila, columna = np.shape(tablero)
    else:
        tablero = np.concatenate((tablero, [a]), axis=0)
        fila, columna = np.shape(tablero)

print(tablero)



[[0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


### Ejercicio 3

- Crea  una  matriz  aleatoria  5x5  y  halla  los  valores mínimo y máximo.
- Normalizar la matriz anterior.

In [137]:
matriz = np.random.rand(5, 5)


valor_minimo = np.min(matriz)
valor_maximo = np.max(matriz)

print("La matriz aleatoria es:\n", matriz)
print("\nEl valor mínimo de la matriz es:", valor_minimo)
print("El valor máximo de la matriz es:", valor_maximo)

La matriz aleatoria es:
 [[0.24371687 0.20575285 0.70913141 0.05752546 0.50298354]
 [0.50477034 0.12909767 0.91383991 0.08717525 0.2539076 ]
 [0.28746827 0.40590116 0.61003354 0.49780937 0.71967687]
 [0.41613048 0.62612067 0.46773954 0.29522387 0.13385657]
 [0.54408281 0.87103815 0.34520823 0.51349331 0.45941603]]

El valor mínimo de la matriz es: 0.05752546457947949
El valor máximo de la matriz es: 0.9138399066176623


In [138]:
# Ejecutar celda anterior
norma = np.linalg.norm(matriz)
matriz_normalizada = matriz / norma

print("La matriz normalizada es:\n", matriz_normalizada)

La matriz normalizada es:
 [[0.09980936 0.08426195 0.29041056 0.0235584  0.20598683]
 [0.20671858 0.05286936 0.37424482 0.03570087 0.10398277]
 [0.11772687 0.16622868 0.24982701 0.20386785 0.29472924]
 [0.1704179  0.25641517 0.19155335 0.12090302 0.05481828]
 [0.22281821 0.35671622 0.14137311 0.21029089 0.18814463]]


In [ ]:
# Se importan los módulos necesarios para la graficación

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Circle

# Función que retorna el campo Eléctrico.

def E(q, r0, x, y):

    """Retorna el vector de campo eléctrico E=(Ex,Ey) de una carga q en r0"""
    den = np.hypot(x-r0[0], y-r0[1])**3
    return q * (x - r0[0]) / den, q * (y - r0[1]) / den


# Puntos de los ejes x e y.

nx, ny = 64, 64

x = np.linspace(-2, 2, nx)

y = np.linspace(-2, 2, ny)

X, Y = np.meshgrid(x, y)


# Crear un multipolo con nq cargas

# count = número de q. En ese caso es 1 dipolo

count = 1
nq = 2**int(count)
charges = []

for i in range(nq):
    q = i%2 * 2 - 1
    charges.append((q, (np.cos(2*np.pi*i/nq), np.sin(2*np.pi*i/nq))))


# Vector de campo eléctrico como componentes separados (Ex,Ey)

Ex, Ey = np.zeros((ny, nx)), np.zeros((ny, nx))

for charge in charges:
    ex, ey = E(*charge, x=X, y=Y)
    Ex += ex
    Ey += ey

fig = plt.figure()
ax = fig.add_subplot(111)

# Dibujar las líneas de flujo con mapa de colores y estilos apropiados.

color = 2 * np.log(np.hypot(Ex, Ey))

ax.streamplot(x, y, Ex, Ey, color=color, linewidth=1, cmap=plt.cm.inferno,
              density=2, arrowstyle='->', arrowsize=1.5)


# Agregar circulos para las cargas.

charge_colors = {True: '#aa0000', False: '#0000aa'}

for q, pos in charges:
    ax.add_artist(Circle(pos, 0.05, color=charge_colors[q>0]))


# Graficar

ax.set_xlabel('$x$')
ax.set_ylabel('$y$')
ax.set_xlim(-2,2)
ax.set_ylim(-2,2)
ax.set_aspect('equal')
plt.show()