In [2]:
import numpy as np

### Ejercicio 1

- Crear una matriz de ceros de tipo entero 3x4.
- Crear una matriz de ceros de tipo entero 3x4 excepto la primera fila que será uno.
- Crear una matriz de ceros de tipo entero 3x4 excepto la última fila que será el rango entre 5 y 8.

In [11]:
a = np.zeros([3, 4])
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
a = np.ones([1, 4])
b = np.zeros([2, 4])

c = np.concatenate((a, b), axis=0)
c

array([[1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [125]:
a = np.arange(5, 9, 1)
b = np.zeros([2, 4])

c = np.concatenate(([a], b), axis=0)
c


array([[5., 6., 7., 8.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Ejercicio 2

- Crea un vector de 10 elementos, siendo los índices impares unos y los índices pares dos.
- Crea un «tablero de ajedrez», con unos en las casillas negras y ceros en las blancas.

In [77]:
a = np.array([])

while np.size(a) < 10:
    if np.size(a) % 2 == 0:
        a = np.concatenate((a, np.array([2])))
    else:
        a = np.concatenate((a, np.array([1])))

print(a)

[2. 1. 2. 1. 2. 1. 2. 1. 2. 1.]


In [135]:
a = np.array([])
b = np.array([])

while np.size(a) < 8:
    if np.size(a) % 2 == 0:
        a = np.concatenate((a, np.array([0])))
    else:
        a = np.concatenate((a, np.array([1])))

while np.size(b) < 8:
    if np.size(b) % 2 == 0:
        b = np.concatenate((b, np.array([1])))
    else:
        b = np.concatenate((b, np.array([0])))

tablero = [a]

fila, columna = np.shape(tablero)
while fila < 8:
    if fila % 2 == 0:
        tablero = np.concatenate((tablero, [b]), axis=0)
        fila, columna = np.shape(tablero)
    else:
        tablero = np.concatenate((tablero, [a]), axis=0)
        fila, columna = np.shape(tablero)

print(tablero)



[[0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [4]:
tablero = np.zeros((8, 8))

for i in range(8):
    for j in range(8):
        if (i + j) % 2 != 0:
            tablero[i][j] = 1

print(tablero)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


### Ejercicio 3

- Crea  una  matriz  aleatoria  5x5  y  halla  los  valores mínimo y máximo.
- Normalizar la matriz anterior.

In [137]:
matriz = np.random.rand(5, 5)


valor_minimo = np.min(matriz)
valor_maximo = np.max(matriz)

print("La matriz aleatoria es:\n", matriz)
print("\nEl valor mínimo de la matriz es:", valor_minimo)
print("El valor máximo de la matriz es:", valor_maximo)

La matriz aleatoria es:
 [[0.24371687 0.20575285 0.70913141 0.05752546 0.50298354]
 [0.50477034 0.12909767 0.91383991 0.08717525 0.2539076 ]
 [0.28746827 0.40590116 0.61003354 0.49780937 0.71967687]
 [0.41613048 0.62612067 0.46773954 0.29522387 0.13385657]
 [0.54408281 0.87103815 0.34520823 0.51349331 0.45941603]]

El valor mínimo de la matriz es: 0.05752546457947949
El valor máximo de la matriz es: 0.9138399066176623


In [138]:
# Ejecutar celda anterior
norma = np.linalg.norm(matriz)
matriz_normalizada = matriz / norma

print("La matriz normalizada es:\n", matriz_normalizada) 

La matriz normalizada es:
 [[0.09980936 0.08426195 0.29041056 0.0235584  0.20598683]
 [0.20671858 0.05286936 0.37424482 0.03570087 0.10398277]
 [0.11772687 0.16622868 0.24982701 0.20386785 0.29472924]
 [0.1704179  0.25641517 0.19155335 0.12090302 0.05481828]
 [0.22281821 0.35671622 0.14137311 0.21029089 0.18814463]]
