In [1]:
import numpy as np

a = np.arange(15).reshape(3, 5)
print(a)
print(a.data)
print(a.dtype.name)
print(a.itemsize)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
int32
4


In [7]:
a = np.zeros(2)

b = np.empty(2)

c = np.ones(2)

d = np.arange(4)

e = np.arange(2, 9, 2)

f = np.linspace(0, 10, num=5)

print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

[0. 0.]
[0. 0.]
[1. 1.]
[0 1 2 3]
[2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]


In [8]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [2]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
print('\n', c)


 [[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [ ]:
rg = np.random.default_rng()